#!/bin/sh
set -e
# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section
# remove extra symlink
[ -h /usr/lib/pkgconfig/svrcore-devel.pc ] && rm -rf /usr/lib/pkgconfig/svrcore-devel.pc

exit 0